spring:
  application:
    name: "Gestion des Missions"
  jpa:
    generate-ddl: true  
        # this allow you to see sql queries in your console
        # usefull for some debugs
        # set this to false for faster db initialisation in createddrop
    show-sql: false 
    properties:
      hibernate:
      # this has not a real chances to become a security concern
      # but just in case set this to false in production
        format_sql: false      
    hibernate:
      ddl-auto: create-drop
    session:
      store-type: jdbc
      timeout: 7200        
  datasource:
    # of course you're supposed to put your own creadentials here
    url: "jdbc:mariadb://localhost:3307/databaseName"
    username: databaseAccountLogin
    password: "1111"
    # driver... really important
    driverClassName: org.mariadb.jdbc.Driver
    